[package]
name = "trading-utils"
version = "0.1.0"
authors = ["Dzenan Jupic <info@dzenanjupic.de>"]
edition = "2018"

[dependencies]
libloading = "0.6.2"
chrono = "0.4.11"
auto_ops = "0.1.0"
serde = {version="1.0.114", features=["derive"]}

[build-dependencies]
rustc_version = "0.2.3"
